apiVersion: v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins-k8s
spec:
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      terminationGracePeriodSecond: 10
      serviceAccount: jenkins
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        - containerPort: 5000
          name: agent
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        livenessProde:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60  #初始化启动后60s后启动探针
          timeoutSeconds: 5
          failureThreshold: 12
        volumeMounts:
        - name: jenkinshome
          subPath: jenkins
          mountPath: /var/jenkins_home #持久化存储挂在目录
        env:
        - name: LIMITS_MEMORY
          valueFrom:
            resourceFiledRef:
              resource: limit.memory
              divisor: 1Mi
        - name: JAVA_OPTS
          value: -Xms$(LIMITS_MEMORY)m -XshowSettings:vm -Dhubson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Duser.timezone=Asia/Shanghai
      securityContext:
        fsGroup: 1000
      volumes:
      - name: jenkins_home
        persistentVolumeClaim:
          claimName: opspvc
