# 创建jenkins用户serviceaccount 
# rbac
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins-k8s


---
# 创建对应账户权限，直接赋予cluster admin权限也是相通
apiVersion: v1
kind: ClusterRole
metadata:
  name: jenkins
rules:
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]
  - apiGroups: [""]   # “” 表明使用core api group
    resources: ["services"]
    verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
# 角色绑定
apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: jenkins
  namespace: jenkins-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins-k8s
